services:
  website-dependencies:
    container_name: website-dependencies
    build:
      dockerfile: Dockerfile
      target: dependencies
    working_dir: /home/lib
    volumes:
      - ./:/home/lib:consistent
  website-node:
    container_name: website-node
    depends_on:
      website-dependencies:
        condition: service_completed_successfully
    build:
      dockerfile: Dockerfile
      target: node
    working_dir: /home/lib
    volumes:
      - ./:/home/lib:consistent
    tty: true
  website:
    container_name: website
    depends_on:
      website-dependencies:
        condition: service_completed_successfully
    build:
      dockerfile: Dockerfile
      target: website
    working_dir: /home/lib
    volumes:
      - ./:/home/lib:consistent
    ports:
      - 5173:5173
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`me.localhost`)
      - traefik.http.routers.website.entryPoints=web
      - traefik.http.services.website.loadbalancer.server.port=5173
  website-reverse-proxy:
    container_name: website-reverse-proxy
    image: traefik:latest
    restart: unless-stopped
    depends_on:
      website:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.reverse-proxy-dashboard.rule=Host(`proxy.me.localhost`)
      - traefik.http.routers.reverse-proxy-dashboard.service=api@internal
      - traefik.http.routers.reverse-proxy-dashboard.entrypoints=web
      - traefik.http.services.reverse-proxy-dashboard.loadbalancer.server.port=80
